/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import Conexao.ConexaoBanco;
import Conexao.Utility;
import br.com.entity.Cliente;
import br.com.entity.Produto;
import br.com.entity.Venda;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenno
 */
public class NewJFrame extends javax.swing.JFrame {
    
    ConexaoBanco conecta = new ConexaoBanco();
    Utility util = new Utility();
    Cliente cliteste = new Cliente();
    Produto prodteste = new Produto();
    Venda vendateste = new Venda();
    Venda salvaprod = new Venda();

    List<Cliente> listaCliente = new ArrayList<>();
    List<Produto> listaProduto = new ArrayList<>();
    List<Venda> listaTotal = new ArrayList<>();
    
    public void listarProduto() {
        //modelo padrão para usar tabela
        DefaultTableModel dados = (DefaultTableModel) Tabela.getModel();
        dados.setNumRows(0); //limpando os dados da tabela

        for (Produto produto : listaProduto) {
            //Object é classe pai de todas as classes
            dados.addRow(new Object[]{
                produto.getId(),
                produto.getNomeProduto(),
                produto.getPrecoProduto(),
                produto.getQuantProduto(),
                produto.subTotal(produto.getPrecoProduto(), produto.getQuantProduto())


            });

        }
    }
    
    public NewJFrame() {
        initComponents();
        preencherProd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        TituloPage = new javax.swing.JLabel();
        PanelDadosDoCliente = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        campoNomeCli = new javax.swing.JTextField();
        labelEnd = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        labelTel = new javax.swing.JLabel();
        campoTel = new javax.swing.JFormattedTextField();
        PesquisarCliente = new javax.swing.JButton();
        ButtonNovoCliente = new javax.swing.JButton();
        labelNome1 = new javax.swing.JLabel();
        campoCodCliente = new javax.swing.JTextField();
        PesqCliente = new javax.swing.JTextField();
        PanelCarrinhoDeCompras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        PanelResumoDaCompra = new javax.swing.JPanel();
        labelSubtotal = new javax.swing.JLabel();
        campoSubtotal = new javax.swing.JFormattedTextField();
        ButtonPagamento = new javax.swing.JButton();
        CancelaCompra = new javax.swing.JButton();
        PanelItemDeCompra = new javax.swing.JPanel();
        labelProduto = new javax.swing.JLabel();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        labelQtd = new javax.swing.JLabel();
        labelPreco = new javax.swing.JLabel();
        qtdProduto = new javax.swing.JTextField();
        precoProduto = new javax.swing.JTextField();
        ButtonConfirmar = new javax.swing.JButton();
        Produtos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(70, 130, 180));
        Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloPage.setBackground(new java.awt.Color(66, 59, 188));
        TituloPage.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        TituloPage.setForeground(new java.awt.Color(250, 250, 250));
        TituloPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPage.setText("Depósito Água Benta");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDadosDoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)))); // NOI18N

        labelNome.setText("Nome");

        labelEnd.setText("Endereço");

        labelTel.setText("Telefone");

        try {
            campoTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelActionPerformed(evt);
            }
        });

        PesquisarCliente.setText("Pesquisar Cliente");
        PesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesquisarClienteMouseClicked(evt);
            }
        });

        ButtonNovoCliente.setText("Cadastrar Novo Cliente");
        ButtonNovoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonNovoClienteMouseClicked(evt);
            }
        });
        ButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovoClienteActionPerformed(evt);
            }
        });

        labelNome1.setText("Código:");

        campoCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodClienteActionPerformed(evt);
            }
        });

        PesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesqClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDadosDoClienteLayout = new javax.swing.GroupLayout(PanelDadosDoCliente);
        PanelDadosDoCliente.setLayout(PanelDadosDoClienteLayout);
        PanelDadosDoClienteLayout.setHorizontalGroup(
            PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosDoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonNovoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDadosDoClienteLayout.createSequentialGroup()
                        .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelEnd)
                            .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(campoNomeCli, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(PanelDadosDoClienteLayout.createSequentialGroup()
                                .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTel))
                                .addGap(15, 15, 15)
                                .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNome1)
                                    .addComponent(campoCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PesqCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PesquisarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelDadosDoClienteLayout.setVerticalGroup(
            PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosDoClienteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(PesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PesquisarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTel)
                    .addComponent(labelNome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDadosDoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonNovoCliente))
        );

        PanelCarrinhoDeCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrinho de Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Produto", "Nome do Produto", "Preço", "Quantidade", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        javax.swing.GroupLayout PanelCarrinhoDeComprasLayout = new javax.swing.GroupLayout(PanelCarrinhoDeCompras);
        PanelCarrinhoDeCompras.setLayout(PanelCarrinhoDeComprasLayout);
        PanelCarrinhoDeComprasLayout.setHorizontalGroup(
            PanelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCarrinhoDeComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelCarrinhoDeComprasLayout.setVerticalGroup(
            PanelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCarrinhoDeComprasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelResumoDaCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total da Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        labelSubtotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelSubtotal.setText("Subtotal:");

        campoSubtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        campoSubtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        ButtonPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonPagamento.setText("Finalizar Compra");
        ButtonPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPagamentoMouseClicked(evt);
            }
        });

        CancelaCompra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CancelaCompra.setText("Cancelar Compra");
        CancelaCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelaCompraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelResumoDaCompraLayout = new javax.swing.GroupLayout(PanelResumoDaCompra);
        PanelResumoDaCompra.setLayout(PanelResumoDaCompraLayout);
        PanelResumoDaCompraLayout.setHorizontalGroup(
            PanelResumoDaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResumoDaCompraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelResumoDaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSubtotal)
                    .addComponent(ButtonPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelResumoDaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelaCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelResumoDaCompraLayout.setVerticalGroup(
            PanelResumoDaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResumoDaCompraLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelResumoDaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSubtotal)
                    .addComponent(campoSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(PanelResumoDaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPagamento)
                    .addComponent(CancelaCompra))
                .addContainerGap())
        );

        PanelItemDeCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item de Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        labelProduto.setText("Produto:");

        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indaia", "Naturagua", "Santa Monica", "Limpida" }));
        jComboBoxProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxProdutoMouseClicked(evt);
            }
        });
        jComboBoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutoActionPerformed(evt);
            }
        });

        labelQtd.setText("Quantidade:");

        labelPreco.setText("Preço:");

        ButtonConfirmar.setText("Incluir no Carrinho");
        ButtonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonConfirmarMouseClicked(evt);
            }
        });

        Produtos.setText("Adicionar Produto");
        Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutosMouseClicked(evt);
            }
        });
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelItemDeCompraLayout = new javax.swing.GroupLayout(PanelItemDeCompra);
        PanelItemDeCompra.setLayout(PanelItemDeCompraLayout);
        PanelItemDeCompraLayout.setHorizontalGroup(
            PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelItemDeCompraLayout.createSequentialGroup()
                .addGroup(PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Produtos)
                    .addGroup(PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelItemDeCompraLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addGroup(PanelItemDeCompraLayout.createSequentialGroup()
                                    .addComponent(labelQtd)
                                    .addGap(4, 4, 4)
                                    .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelItemDeCompraLayout.createSequentialGroup()
                                    .addComponent(labelPreco)
                                    .addGap(33, 33, 33)
                                    .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(PanelItemDeCompraLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(ButtonConfirmar))
                        .addGroup(PanelItemDeCompraLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(labelProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelItemDeCompraLayout.setVerticalGroup(
            PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelItemDeCompraLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Produtos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProduto)
                    .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQtd)
                    .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelItemDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreco)
                    .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(ButtonConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelItemDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelDadosDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelResumoDaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDadosDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelItemDeCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelResumoDaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelActionPerformed

    private void preencherProd(){
        conecta.conexao();
        
        conecta.executasql("select * from produto order by nome_prod");
        try {
            conecta.rs.first();
            jComboBoxProduto.removeAllItems();
            do{
                jComboBoxProduto.addItem(conecta.rs.getString("nome_prod"));
                
            
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        conecta.desconexao();
    }
    
    private void ButtonNovoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNovoClienteMouseClicked

        cliteste.setNomeCliente(campoNomeCli.getText());
        cliteste.setEndCliente(campoEndereco.getText());
        cliteste.setTelCliente(campoTel.getText());
        util.SalvarCli(cliteste);
        
    }//GEN-LAST:event_ButtonNovoClienteMouseClicked

    private void ButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNovoClienteActionPerformed

    private void ButtonConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfirmarMouseClicked
        Produto produto = new Produto();

        produto.setId(1);
        produto.setNomeProduto(jComboBoxProduto.getSelectedItem().toString());
        produto.setPrecoProduto(Double.parseDouble(precoProduto.getText()));
        produto.setQuantProduto(Integer.parseInt(qtdProduto.getText()));

        listaProduto.add(produto);
        listarProduto();
        
        salvaprod.setQtdProd(Integer.parseInt(qtdProduto.getText()));
        salvaprod.totalVenda(Double.parseDouble(precoProduto.getText()), Integer.parseInt(qtdProduto.getText()));
        campoSubtotal.setText("R$ " +String.valueOf(salvaprod.getValorvenda()));
        
    }//GEN-LAST:event_ButtonConfirmarMouseClicked

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutosMouseClicked
  
        TodosProdutos prod = new TodosProdutos();
        prod.setVisible(true);
    }//GEN-LAST:event_ProdutosMouseClicked

    private void CancelaCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelaCompraMouseClicked

        JOptionPane.showMessageDialog(null, "Até mais.");
        System.exit(0);
    }//GEN-LAST:event_CancelaCompraMouseClicked

    private void PesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesquisarClienteMouseClicked
        cliteste.setPesquisa(PesqCliente.getText());
        Cliente model = util.Buscacliente(cliteste);
        campoCodCliente.setText(String.valueOf(model.getIdCliente()));
        campoNomeCli.setText(model.getNomeCliente());
        campoEndereco.setText(model.getEndCliente());
        campoTel.setText(model.getTelCliente());
        ButtonNovoCliente.setEnabled(false);
        
    }//GEN-LAST:event_PesquisarClienteMouseClicked

    private void PesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesqClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesqClienteActionPerformed

    private void campoCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodClienteActionPerformed
        campoCodCliente.setVisible(false);
    }//GEN-LAST:event_campoCodClienteActionPerformed

    private void jComboBoxProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxProdutoMouseClicked

    }//GEN-LAST:event_jComboBoxProdutoMouseClicked

    private void jComboBoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutoActionPerformed
        prodteste.setPesquisaprod((String) jComboBoxProduto.getSelectedItem());
        Produto model = util.Buscaprod(prodteste);
        precoProduto.setText(String.valueOf(model.getPrecoProduto()));
        qtdProduto.setText("");
    }//GEN-LAST:event_jComboBoxProdutoActionPerformed

    private void ButtonPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPagamentoMouseClicked
        vendateste.setIdCliente(Integer.parseInt(campoCodCliente.getText()));
        vendateste.setQtdProd(salvaprod.getQtdProd());
        vendateste.setValorvenda(salvaprod.getValorvenda());
        util.SalvarVenda(vendateste);
        
        JOptionPane.showMessageDialog(null, "Valor Total da Compra: " + vendateste.getValorvenda() +"\nCompra realizada. Agradecemos a preferência e volte sempre!");
        System.exit(0);
    }//GEN-LAST:event_ButtonPagamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfirmar;
    private javax.swing.JButton ButtonNovoCliente;
    private javax.swing.JButton ButtonPagamento;
    private javax.swing.JButton CancelaCompra;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel PanelCarrinhoDeCompras;
    private javax.swing.JPanel PanelDadosDoCliente;
    private javax.swing.JPanel PanelItemDeCompra;
    private javax.swing.JPanel PanelResumoDaCompra;
    private javax.swing.JTextField PesqCliente;
    private javax.swing.JButton PesquisarCliente;
    private javax.swing.JButton Produtos;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel TituloPage;
    private javax.swing.JTextField campoCodCliente;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNomeCli;
    private javax.swing.JFormattedTextField campoSubtotal;
    private javax.swing.JFormattedTextField campoTel;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEnd;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JLabel labelQtd;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTel;
    private javax.swing.JTextField precoProduto;
    private javax.swing.JTextField qtdProduto;
    // End of variables declaration//GEN-END:variables
}
