/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import javax.swing.JOptionPane;

/**
 *
 * @author lenno
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        TituloPage = new javax.swing.JLabel();
        TelaMain = new javax.swing.JTabbedPane();
        CadastrarCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NovoCliente = new javax.swing.JButton();
        SalvarCliente = new javax.swing.JButton();
        CancelarCadastro = new javax.swing.JButton();
        ExcluirCliente = new javax.swing.JButton();
        CadastrarCliente1 = new javax.swing.JPanel();
        LabelCodP = new javax.swing.JLabel();
        CampoCodP = new javax.swing.JTextField();
        LabelNomeP = new javax.swing.JLabel();
        CampoNomeP = new javax.swing.JTextField();
        LabelCPFP = new javax.swing.JLabel();
        LabelTelP = new javax.swing.JLabel();
        CampoCpfP = new javax.swing.JFormattedTextField();
        CampoTelP = new javax.swing.JFormattedTextField();
        CampoEndP = new javax.swing.JTextField();
        LabelEndP = new javax.swing.JLabel();
        ButtonPesquisarP = new javax.swing.JButton();
        ButtonEditarP = new javax.swing.JButton();
        ButtonCancelarP = new javax.swing.JButton();
        ButtonExcluirP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setPreferredSize(new java.awt.Dimension(800, 530));

        Header.setBackground(new java.awt.Color(70, 130, 180));
        Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TituloPage.setBackground(new java.awt.Color(66, 59, 188));
        TituloPage.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        TituloPage.setForeground(new java.awt.Color(250, 250, 250));
        TituloPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPage.setText("Sistema de Clientes");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloPage, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Código do Cliente:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Nome do Cliente:");

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Telefone:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Endereço:");

        NovoCliente.setText("Novo");
        NovoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NovoClienteMouseClicked(evt);
            }
        });

        SalvarCliente.setText("Salvar");

        CancelarCadastro.setText("Cancelar");

        ExcluirCliente.setText("Excluir");

        javax.swing.GroupLayout CadastrarClienteLayout = new javax.swing.GroupLayout(CadastrarCliente);
        CadastrarCliente.setLayout(CadastrarClienteLayout);
        CadastrarClienteLayout.setHorizontalGroup(
            CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarClienteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CadastrarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CadastrarClienteLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(352, 352, 352))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastrarClienteLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastrarClienteLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CadastrarClienteLayout.createSequentialGroup()
                                    .addComponent(NovoCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(SalvarCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ExcluirCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CancelarCadastro))
                                .addGroup(CadastrarClienteLayout.createSequentialGroup()
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextField2))))))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        CadastrarClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4});

        CadastrarClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CancelarCadastro, ExcluirCliente, NovoCliente, SalvarCliente});

        CadastrarClienteLayout.setVerticalGroup(
            CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarClienteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoCliente)
                    .addComponent(SalvarCliente)
                    .addComponent(ExcluirCliente)
                    .addComponent(CancelarCadastro))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        TelaMain.addTab("Cadastrar Cliente", CadastrarCliente);

        LabelCodP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        LabelCodP.setText("Código do Cliente:");

        CampoCodP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodPActionPerformed(evt);
            }
        });

        LabelNomeP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        LabelNomeP.setText("Nome do Cliente:");

        CampoNomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomePActionPerformed(evt);
            }
        });

        LabelCPFP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        LabelCPFP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelCPFP.setText("CPF:");

        LabelTelP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        LabelTelP.setText("Telefone:");

        try {
            CampoCpfP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoCpfP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCpfPActionPerformed(evt);
            }
        });

        try {
            CampoTelP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        CampoEndP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEndPActionPerformed(evt);
            }
        });

        LabelEndP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        LabelEndP.setText("Endereço:");

        ButtonPesquisarP.setText("Pesquisar");
        ButtonPesquisarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPesquisarPMouseClicked(evt);
            }
        });

        ButtonEditarP.setText("Editar");

        ButtonCancelarP.setText("Cancelar");

        ButtonExcluirP.setText("Excluir");

        javax.swing.GroupLayout CadastrarCliente1Layout = new javax.swing.GroupLayout(CadastrarCliente1);
        CadastrarCliente1.setLayout(CadastrarCliente1Layout);
        CadastrarCliente1Layout.setHorizontalGroup(
            CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarCliente1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CadastrarCliente1Layout.createSequentialGroup()
                        .addComponent(LabelEndP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoEndP, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CadastrarCliente1Layout.createSequentialGroup()
                            .addComponent(LabelCodP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoCodP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(352, 352, 352))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastrarCliente1Layout.createSequentialGroup()
                            .addComponent(LabelNomeP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CampoNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastrarCliente1Layout.createSequentialGroup()
                            .addComponent(LabelCPFP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CadastrarCliente1Layout.createSequentialGroup()
                                    .addComponent(ButtonPesquisarP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonEditarP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonExcluirP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonCancelarP))
                                .addGroup(CadastrarCliente1Layout.createSequentialGroup()
                                    .addComponent(CampoCpfP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(LabelTelP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoTelP))))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        CadastrarCliente1Layout.setVerticalGroup(
            CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarCliente1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomeP)
                    .addComponent(CampoNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEndP)
                    .addComponent(CampoEndP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCPFP)
                    .addComponent(LabelTelP)
                    .addComponent(CampoCpfP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoTelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPesquisarP)
                    .addComponent(ButtonEditarP)
                    .addComponent(ButtonExcluirP)
                    .addComponent(ButtonCancelarP))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        TelaMain.addTab("Pesquisar Cliente", CadastrarCliente1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TelaMain, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 63, Short.MAX_VALUE)
                    .addComponent(TelaMain)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPesquisarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPesquisarPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPesquisarPMouseClicked

    private void CampoEndPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEndPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEndPActionPerformed

    private void CampoCpfPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCpfPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCpfPActionPerformed

    private void CampoNomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomePActionPerformed

    private void CampoCodPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodPActionPerformed

    private void NovoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovoClienteMouseClicked
        JOptionPane.showMessageDialog(null, "Cadastrado");
    }//GEN-LAST:event_NovoClienteMouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelarP;
    private javax.swing.JButton ButtonEditarP;
    private javax.swing.JButton ButtonExcluirP;
    private javax.swing.JButton ButtonPesquisarP;
    private javax.swing.JPanel CadastrarCliente;
    private javax.swing.JPanel CadastrarCliente1;
    private javax.swing.JTextField CampoCodP;
    private javax.swing.JFormattedTextField CampoCpfP;
    private javax.swing.JTextField CampoEndP;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNomeP;
    private javax.swing.JFormattedTextField CampoTelP;
    private javax.swing.JButton CancelarCadastro;
    private javax.swing.JButton ExcluirCliente;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LabelCPFP;
    private javax.swing.JLabel LabelCodP;
    private javax.swing.JLabel LabelEndP;
    private javax.swing.JLabel LabelNomeP;
    private javax.swing.JLabel LabelTelP;
    private javax.swing.JButton NovoCliente;
    private javax.swing.JButton SalvarCliente;
    private javax.swing.JTabbedPane TelaMain;
    private javax.swing.JLabel TituloPage;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
